dist: bionic
language: Rust
rust:
- stable
- beta
- nightly

cache:
  directories:
  - $TRAVIS_BUILD_DIR/target

env:
  global:
  - PATH="$HOME/.cargo/bin:$PATH"

install:
- ci/travis/install.sh

script:
- cargo tarpaulin -v --out Xml --ciserver travis-ci

after_script:
- curl -SsL "https://codecov.io/bash" | bash -s - -y ci/codecov.yml

before_cache:
- cargo cache -a

deploy:
- provider: cargo
  token:
    secure: t8+U2YBZrzLM26fyQBZ80BANxGtrsMWmsxADFC1xavR3YnC2scRHz5yA6ggJFgJTS0HsEL+WyUqQel07dRdnkoL4IrPPLQeP6A2iciWgLt8lXtkYHz9/P1bZtFhuiRHzn1iyjGIU+na8S3V7OMCahas3rEJmQ/DzwuVfEOb1cTfr6gpjdUEm03dEG6a9XjbqEOgi1aeg86RjXZNLqi/scxkMsPbUZ7xwIFxun7Q8K5HwWOTMfvyupABczKvGMIJ6MI65HAcON3PwmPmCqD3A/Z9ChAnwQPsjgtOGCYxemyyfABR4jF3iwOaOWJz/GtgTSaZ4CsK+euweEx14SouMh0gFnLP044LsnS/KHUNyMmKCfWwG+ZDEyORm4jdxPa8Vl5ikxy1wzJNXxfPMp1w5gHYsMgGmFnVapLVAMTQ601QclG6K05RQ2ZvAsFwp2Lu5etRsxlXJOTmKy3FHN2nxtMbOuTQ3HYn++C+B0knhoZeWlk86Vy9tEMJWndZckoDlbZnbHtmD+25oyk9bwcSK6GwkY3aGJ212FWIYGQgc6v1Y7EKxspI2zLW/TiCNDHQbAfoTnPI2bKmFObDEDE41oUuzbHwZJPqUjIa/joAHHmNVMM6EdUYibSrQ7ba2roTF/92HTNGeVenHZCRoPPjJv0DKLeISaMoWgJaNBYpQKP8=
  on:
    rust: stable
    tags: true
- provider: script
  script: ci/travis/deploy.sh
  on:
    rust: stable
    tags: true

notifications:
  email:
  - althonosdev@gmail.com
